version: "2"

run:
  timeout: 5m
  issues-exit-code: 1

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - funlen
    - cyclop
    - lll
    - forbidigo
  exclusions:
    paths:
      - docs
      - mocks
      - scripts
  settings:
    dupl:
      threshold: 250
    lll:
      line-length: 160
    goconst:
      min-len: 2
      min-occurrences: 3
    errcheck:
      exclude-functions:
        - (io.Closer).Close
    cyclop:
      max-complexity: 10
    funlen:
      lines: 50
